### ISSUE TITLE
Can i add an API?

### ISSUE THREAD

**Issue by Erkam246** [Frago9876543210/MCPE-Proxy#10]

**Comment by SuperOP535** [comment]
what do u mean we can't read your mind

**Comment by Erkam246** [comment]
Like $this->getProxy()->getClient()->sendMessage("LOL");

**Comment by Frago9876543210** [comment]
use packets

**Comment by Erkam246** [comment]
I want to make a pull request to add this functions

**Comment by Frago9876543210** [comment]
Nobody forbids you to create pull requests
