### ISSUE TITLE
svilex is selling your proxy

### ISSUE THREAD

**Issue by lukeeey** [Frago9876543210/MCPE-Proxy#16]
Did you know your proxy is being sold at https://gist.github.com/svilex/0409004e9475153590bfa33b61b0f229

**Comment by Frago9876543210** [comment]
This is other proxy

**Comment by lukeeey** [comment]
Someone sent me the svilex's proxy and it has your name in it

**Comment by Thunder33345** [comment]
it's probably FAKE!!!
