### ISSUE TITLE
Uncaught Error: Class 'proxy\Proxy' not found

### ISSUE THREAD

**Issue by LewBr** [Frago9876543210/MCPE-Proxy#19]
Fatal error: Uncaught Error: Class 'proxy\Proxy' not found in \PocketMine-MP\MCBE-Proxy-master\src\proxy\start.php:27
Stack trace:
#0 {main}
  thrown in \PocketMine-MP\MCBE-Proxy-master\src\proxy\start.php on line 27

**Comment by Frago9876543210** [comment]
```composer install```
