### ISSUE TITLE
????

### ISSUE THREAD

**Issue by Rateek** [Frago9876543210/MCPE-Proxy#3]
Fatal error: Uncaught Error: Class 'pocketmine\utils\Config' not found in /root/                                                                   proxy/src/proxy/start.php:22
Stack trace:
#0 {main}
  thrown in /root/proxy/src/proxy/start.php on line 22

What? ...

**Comment by ghost** [comment]
You must use autostart.php

**Comment by Rateek** [comment]
@kaliiks What autostart

**Comment by Frago9876543210** [comment]
you run it on Windows?

**Comment by SuperOP535** [comment]
use git clone if you didn't

**Comment by Rateek** [comment]
@Frago9876543210 No linux

**Comment by Frago9876543210** [comment]
@Rateek use install.sh

**Comment by ghost** [comment]
@Rateek \vendor\autostart

**Comment by ghost** [comment]
It's generated automatically by composer

**Comment by inxomnyaa** [comment]
Because of the descriptive title of this issue:

What can i do with the proxy?

**Comment by Johnmacrocraft** [comment]
@thebigsmileXD ~~You can have [advantage](https://en.wikipedia.org/wiki/Cheating#Video_games) in server~~

**Comment by SuperOP535** [comment]
:')

**Comment by Johnmacrocraft** [comment]
@SuperOP535 ?

**Comment by SuperOP535** [comment]
@Johnmacrocraft goto discord pls
