### ISSUE TITLE
Error DATA_PACKET

### ISSUE THREAD

**Issue by ghost** [Frago9876543210/MCPE-Proxy#4]
I get this error:
Fatal error: Uncaught Error: Class 'raklib\protocol\DATA_PACKET_1' not found in C:\Users\uzivatel\Downloads\MCPE-Proxy-master\MCPE-Proxy-master\src\proxy\Pool.php:67
Stack trace:
#0 C:\Users\uzivatel\Downloads\MCPE-Proxy-master\MCPE-Proxy-master\src\proxy\Pool.php(48): proxy\Pool::registerPackets()
#1 C:\Users\uzivatel\Downloads\MCPE-Proxy-master\MCPE-Proxy-master\src\proxy\Proxy.php(188): proxy\Pool::getPacketFromPool(5)
It happens when I try join server file raklib\protocol\DATA_PACKET1.php really is there so I don't understand

**Comment by ghost** [comment]
Please help

**Comment by ghost** [comment]
I tried moving files to another directory or same where pool.php is but it still display error
Maybe it's because of _ in file names?
I'm running windows
php 7.2

**Comment by Frago9876543210** [comment]
clone raklib & spl

**Comment by ghost** [comment]
yes I cloned all files are there

**Comment by ghost** [comment]
When I rename it and use without _ like DATAPACKET3 it works lol
Why when in pmmp it working with _ :D

**Comment by Frago9876543210** [comment]
@kaliiks that strange)

**Comment by ghost** [comment]
Solved by renaming all files
