### ISSUE TITLE
Block packet

### ISSUE THREAD

**Issue by debil9877654321** [Frago9876543210/MCPE-Proxy#6]
For example when client send message (text packet) I want to close it, but this looks to be bugged, is that right? I still send the packet to server when I cancel sending it.

**Comment by Frago9876543210** [comment]
Canceling a packet results in the queue being broken.

**Comment by debil9877654321** [comment]
Problem of your proxy is server send packet directly to the client and your proxy is only reading it, but you have to connect player trough the proxy so the packets will go like this:
![image](https://user-images.githubusercontent.com/33634290/34905982-0465e9fc-f864-11e7-9e5c-b94a366834a6.png)
but currently it's like this
![image](https://user-images.githubusercontent.com/33634290/34906000-3b4b7b58-f864-11e7-8795-6d4baf8baa47.png)
I don't know to draw :,D

**Comment by debil9877654321** [comment]
I think you have to make it catch 0x01 packet with player data, but I think you must write your own system to read the packages because in pocketmine raklib it does not catch for some reason as I checked.

**Comment by debil9877654321** [comment]
socket receive catch 0x01, so you only have to decode it by another way I think.

**Comment by Frago9876543210** [comment]
@debil9877654321 The problem is that the MCPE has a queue of packages and their confirmation.

**Comment by debil9877654321** [comment]
Oh, and how to do it then?

**Comment by Frago9876543210** [comment]
Idk

**Comment by debil9877654321** [comment]
Maybe dkt know, you can try ask him.

**Comment by SuperOP535** [comment]
rip

**Comment by Frago9876543210** [comment]
To block client packet need send ACK with right seq number. @Yexeed already tried to block the client's package and it's was done, but with some bugs. Now we need to come up with a better implementation of packet blocking.

**Comment by Frago9876543210** [comment]
e4234a7799648893fa14c6c8a0920326aeb869fe
