### ISSUE TITLE
Ubuntu 14.0

### ISSUE THREAD

**Issue by pranavbhuv** [Frago9876543210/MCPE-Proxy#7]
Can you make an Ubuntu installation guide

**Comment by debil9877654321** [comment]
The guide in readme.md is working for ubuntu.

**Comment by pranavbhuv** [comment]
there is no script @debil9877654321

**Comment by debil9877654321** [comment]
script for what?

**Comment by pranavbhuv** [comment]
installAtion

**Comment by debil9877654321** [comment]
? Click start.sh
